services:
  crypto-monitor:
    image: ghcr.io/yoanndelattre/crypto-monitor:main
    container_name: crypto-monitor
    hostname: crypto-monitor
    restart: always
    env_file:
      - .env
    volumes:
      - crypto-monitor_data:/app/data
      - ./wallets.json:/app/wallets.json

volumes:
  crypto-monitor_data: